name: cusor_patcher
description: A Cursor patcher application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # fast_gbk is a package that has gbk utils
  fast_gbk: ^1.0.0
  # url_launcher can launch url
  url_launcher: ^6.2.3
  # tray_manager allows Flutter desktop apps to defines system tray
  tray_manager: ^0.3.0
  # window_manager allows Flutter desktop apps to control window
  window_manager: ^0.4.3
  # collection is a package that has some useful collection utils
  collection: ^1.19.0
  # flutter_riverpod is a package that provides state management
  flutter_riverpod: ^2.6.1
  # shared_preferences is a package that provides persistent storage
  shared_preferences: ^2.3.1
  # screen_retriever is a package that provides screen info
  screen_retriever: ^0.2.0
  # launch_at_startup is a package that provides launch at startup
  launch_at_startup: ^0.3.1
  # package_info_plus is a package that provides package info
  package_info_plus: ^8.0.1
  # file_selector is used to choose working dir
  file_selector: ^1.0.2
  # http is used to check upgrade
  http: ^1.2.2
  dio: ^5.4.0
  archive: ^3.4.5
  #i18n
  slang: ^3.32.0
  slang_flutter: ^3.32.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  path_provider: ^2.1.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  go_router: ^14.8.0
  riverpod_annotation: ^2.6.1
  cherry_toast: ^1.12.0
  path: ^1.8.3
  sqlite3: ^2.1.0
  sqlite3_flutter_libs: ^0.5.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.11
  freezed: ^2.5.2
  slang_build_runner: ^3.32.0
  json_serializable: ^6.7.1
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.1

flutter_launcher_icons:
  image_path: "assets\\cursor.png"
  windows:
    generate: true
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true

flutter:
  uses-material-design: true

  assets:
    - assets/cursor.ico
    - assets/cursor.png
