name: Bug Report
description: Submit discovered bugs
labels: ['bug']

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report! Please ensure the bug report filed is detailed and meaningful.
        If you are having problems with usage, consider asking in the [community](https://github.com/Xmarmalade/alisthelper/discussions), or sponsoring to get answers.
        Before filling out a bug report, please make sure you have upgraded to the latest stable version, read the [documentation](https://github.com/Xmarmalade/alisthelper/blob/master/README.md) and [Wiki](https://github.com/Xmarmalade/alisthelper/wiki), and provide all the information required by this template, otherwise the issue will be closed.

  - type: textarea
    id: what-expected
    attributes:
      label: What is expected?
      placeholder: Tell us what you expect!
    validations:
      required: true

  - type: textarea
    id: actual-happened
    attributes:
      label: What is actually happening?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: What version of our software are you running?
    validations:
      required: true

  - type: input
    id: platform-info
    attributes:
      label: Platform information
      description: Please provide your platform information.
      placeholder: 'Windows 10 Home (Build 22621)'
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Additional info
      description: logs, errors, etc.
      render: shell
    validations:
      required: true

  - type: checkboxes
    id: docs
    attributes:
      label: The document does not contain a solution to this problem
      options:
        - label: I have read the [documentation](https://github.com/Xmarmalade/alisthelper/wiki).
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: This is not a duplicated issue
      options:
        - label: I have searched [existing issues](https://github.com/Xmarmalade/alisthelper/issues) to ensure this bug has not already been reported.
          required: true

  - type: checkboxes
    id: relate
    attributes:
      label: This is not an irrelevant issue.
      options:
        - label:  The configurations of my alist and rclone are correct, the problem lies with alist helper.
          required: true
