name: Feature Request
description: Submit a new feature request
labels: ['enhancement']

body:

  - type: markdown
    attributes:
      value: |
        Please ensure the feature requested is not listed in [documentation](https://github.com/Xmarmalade/alisthelper/blob/master/README.md) or [issue](https://github.com/Xmarmalade/alisthelper/issues), and provide all the information required by this template.
        Otherwise the issue will be closed immediately.

  - type: textarea
    id: feature
    attributes:
      label: What feature is it?
      placeholder: Please describe the feature you want to see.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem does this feature solve?
      placeholder: Please describe the problem this feature solves.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Additional description
      placeholder: Any additional description.

  - type: checkboxes
    id: terms
    attributes:
      label: This is not a duplicate feature request or a feature request unrelated to Alist Helper itself.
      options:
        - label: I have searched [existing issues](https://github.com/Xmarmalade/alisthelper/issues) to ensure This is not a duplicate feature request or a feature request unrelated to Alist Helper itself.
          required: true
          
  - type: checkboxes
    id: sponsor
    attributes:
      label: I want to support Alist Helper and I have donated / sponsored Alist Helper
      options:
        - label: I want to support Alist Helper and I have donated / sponsored to Alist Helper
